export default {
  bridgeApi: 'https://bridgeapi.anyswap.exchange',
  netapi: 'https://netapi.anyswap.net',
  enterApp: 'https://app.multichain.org',
  explorerUrl: 'https://scan.multichain.org',
  docUrl: 'https://docs.multichain.org/',
  github: 'https://github.com/anyswap',
  telegram: 'https://t.me/anyswap',
  medium: 'https://medium.com/multichainorg',
  twitter: 'https://twitter.com/MultichainOrg',
  coinmarketcap: 'https://coinmarketcap.com/currencies/multichain/',
  coingecko: 'https://www.coingecko.com/en/coins/multichain',
  multidao: 'https://discord.gg/sxqcWn7std',
  anyCall: 'https://anycall.multichain.org/',
}